private_diary/diary/urls.py
from django.urls import path

from.import views


app_name = 'diary'
urlpatterns = [
    path('',views.IndexView.as_view(),name = "index"),
    path('table',views.TableView.as_view(),name = "table"),
]

private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('diary.urls')),
]

private_diary/diary/models.py
from django.db import models

# Create your models here.

private_diary/diary/views.py
from django.views import generic
from django.shortcuts import render    
import json
import csv
import requests


        #初期設定

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "index.html"


class TableView(generic.TemplateView):
    template_name = "index2.html"

    def get(self,request,*args,**kwatgs,):
        KEYID = "da4e1585e099dac608d681acf6b4e042"
        PREF = "PREF41"
        areacode_l = "AREAL5152"
        PARAMS = {
            "keyid": KEYID,
            "pref": PREF,
            "areacode_l": areacode_l,
        }
        json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
        response = json.loads(json_res)
        if "error" in response:
            return print("エラーが発生しました！")
        if "category" in request.GET:
            param_value = request.GET.get("category")
            if param_value == "和食":
                category_l = "RSFST01000"
                PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "category_l": category_l,
                }
                json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
                response = json.loads(json_res)
            elif param_value == "洋食":
                category_l = "RSFST13000"
                PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "category_l": category_l,
                }
                json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
                response = json.loads(json_res)
            elif param_value == "中華":
                category_l = "RSFST14000"
                PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "category_l": category_l,
                }
                json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
                response = json.loads(json_res)
            elif param_value == "喫茶店・カフェ":
                category_l = "RSFST18000"
                PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "category_l": category_l,
                }
                json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
                response = json.loads(json_res)
            elif param_value == "ファミレス":
                category_l = "RSFST20000"
                PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "category_l": category_l,
                }
                json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
                response = json.loads(json_res)
                
            elif param_value == "居酒屋":
                category_l = "RSFST09000"
                PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "category_l": category_l,
                }
                json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
                response = json.loads(json_res)
        if "namae" in request.GET:
            freeword = request.GET.get("namae")
            PARAMS = {
                    "keyid": KEYID,
                    "pref": PREF,
                    "areacode_l": areacode_l,
                    "freeword": freeword
                }
            json_res = requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/",params=PARAMS).text
            response = json.loads(json_res)
        store_list = [] 
        for i in response['rest'] :
            store_list.append({
                "name":i["name"],
                "address":i["address"],
                "tel":i["tel"],
                "url":i["url"],
            })
        print(type(response))
        return render(request,"index2.html",{"store_list":store_list})

private_diary/diary/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>
            唐津飲食店検索ページ
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
    </head>
    <body>
        <header>
            <div id="header">
                <div class="image">
                    <h1 class="title_1">
                        唐津市　飲食店検索
                    </h1>
                    <form action="{% url 'diary:table' %}" method="get">
                        <p>
                            店名：<input type="text" name="namae" size="40" maxlength="20">   
                            <input type="submit" value="検索">
                        </p>
                    </form>
                </div>
            </div>
        </header>
        <main id="main">
            <div class="image_center">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3328.968953584003!2d129.96593731557434!3d33.45011538077399!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x356a7863814716bb%3A0x5f6704468603619b!2z5ZSQ5rSl5biC5b255omA!5e0!3m2!1sja!2sjp!4v1605333640632!5m2!1sja!2sjp" width="353" height="396" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </main>
        <side>
            <div id="side">
                <div class="box">
                    <h2>
                        カテゴリー
                    </h2>
                        <div class="boxBody">
                            <form action="{% url 'diary:table' %}">
                                <button  method="get" type="sabmit" name="category" value="和食">
                                ・和食　　　　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="洋食">
                                ・洋食　　　　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="中華">
                                ・中華　　　　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="喫茶店・カフェ">
                                ・喫茶店・カフェ
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="ファミレス">
                                ・ファミレス　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="居酒屋">
                                    ・居酒屋　　　　
                                </button>
                            </form>
                        </div>
                        
               
                </div>
            </div>
        </side>
           <footer id="footer">
               <div class="mokuji">
                    <h3>
                        運営しているSNS
                    </h3>
                </div>
                <li>
                    <a href="https://saga-jpn.hatenablog.com/archive">
                        ほのぼの日記ブログ
                    </a>
                </li>
                <li>
                    <a href="https://saga-jpn.hatenablog.jp/archive">
                        透羽の商品紹介ブログ
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/Saga_jpn">
                        Twitter
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/sagan.jpn/">
                        Facebook
                    </a>
                </li>
           </footer>  
    </body>
</html>

private_diary/diary/templates/index2.htm
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>
            唐津飲食店検索ページ
        </title>
        <link rel="stylesheet" href="stylesheet.css">
    </head>
    <body>
        <header>
            <div id="header">
                <div class="image">
                    <h1 class="title_1">
                        唐津市　飲食店検索
                    </h1>
                    <form method="get">
                        <p>
                            店名：<input type="text" name="namae" size="40" maxlength="20">   
                            <input type="submit" value="検索">
                        </p>
                    </form>
                </div>
            </div>
        </header>
        <main id="main">
            
        </main>
        <side>
            <div id="side">
                <div class="box">
                    <h2>
                        カテゴリー
                    </h2>
                    <form method="get">
                        <div class="boxBody">
                            <ul>
                                <button>
                                ・モーニング　　
                                </button>
                                <button>
                                ・ランチ　　　　
                                </button>
                                <button>
                                ・ディナー　　　
                                </button>
                                <button>
                                ・喫茶店・カフェ
                                </button>
                                <button>
                                ・ファミレス　　
                                </button>
                                <button>
                                ・居酒屋　　　　
                                </button>
                            </ul>
                        </div>
                        
                    </form>
                </div>
            </div>
        </side>
           <footer id="footer">
               <div class="mokuji">
                    <h3>
                        運営しているSNS
                    </h3>
                </div>
                <li>
                    <a href="https://saga-jpn.hatenablog.com/archive">
                        ほのぼの日記ブログ
                    </a>
                </li>
                <li>
                    <a href="https://saga-jpn.hatenablog.jp/archive">
                        透羽の商品紹介ブログ
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/Saga_jpn">
                        Twitter
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/sagan.jpn/">
                        Facebook
                    </a>
                </li>
           </footer>  
    </body>
</html>

private_diary/diary/templates/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>
            唐津飲食店検索ページ
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
    </head>
    <body>
        <header>
            <div id="header">
                <div class="image">
                    <h1 class="title_1">
                        唐津市　飲食店検索
                    </h1>
                    <form action="{% url 'diary:table' %}" method="get">
                        <p>
                            店名：<input type="text" name="namae" size="40" maxlength="20">   
                            <input type="submit" value="検索">
                        </p>
                    </form>
                </div>
            </div>
        </header>
        <main id="main">
            {% for value in store_list %}
                <h3>
                    店舗名　【{{value.name}}】
                </h3>
                <h5>
                    住所　：{{value.address}}
                </h5>
                <h5>
                    電話　：{{value.tel}}
                </h5>
                <h65>
                    リンク　：<a href="{{value.url}}">{{value.name}}ホームページ</a>
                </h5>
                <h5>
                    ---------------------------------------------------------------
                </h5>
            {% endfor %}
        </main>
        <side>
            <div id="side">
                <div class="box">
                    <h2>
                        カテゴリー
                    </h2>
                        <div class="boxBody">
                           <form action="{% url 'diary:table' %}">
                                <button  method="get" type="sabmit" name="category" value="和食">
                                ・和食　　　　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="洋食">
                                ・洋食　　　　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="中華">
                                ・中華　　　　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="喫茶店・カフェ">
                                ・喫茶店・カフェ
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="ファミレス">
                                ・ファミレス　　
                                </button>
                            </form>
                            <form action="{% url 'diary:table' %}">
                                <button method="get" type="sabmit" name="category" value="居酒屋">
                                    ・居酒屋　　　　
                                </button>
                            </form>
                        </div>
                </div>
            </div>
        </side>
           <footer id="footer">
               <div class="mokuji">
                    <h3>
                        運営しているSNS
                    </h3>
                </div>
                <li>
                    <a href="htstps://saga-jpn.hatenablog.com/archive">
                        ほのぼの日記ブログ
                    </a>
                </li>
                <li>
                    <a href="https://saga-jpn.hatenablog.jp/archive">
                        透羽の商品紹介ブログ
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/Saga_jpn">
                        Twitter
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/sagan.jpn/">
                        Facebook
                    </a>
                </li>
           </footer>  
    </body>
</html>